### ISSUE TITLE
Problem with core.typed

### ISSUE THREAD

**Issue by divs1210** [clojure-emacs/squiggly-clojure#53] opened 2018-04-13 21:52 UTC
Hi!
I'm using `0.1.9-SNAPSHOT` and get the following error a few seconds after `cider-connect`:
```
core.typed:There was previously an unrecoverable internal error while loading core.typed. Please restart your process.
```
This persists, even on running
`lein do clean, repl`

My `profiles.clj` is as follows:
```
{:repl {:plugins [[cider/cider-nrepl "0.16.0"]
                  [refactor-nrepl "2.3.1"]]
        :dependencies [^:replace [org.clojure/tools.nrepl "0.2.12"]
                       [venantius/pyro "0.1.2"]
                       [acyclic/squiggly-clojure "0.1.9-SNAPSHOT"
                        :exclusions [org.clojure/tools.reader]]]
        :injections [;; better errors
                     (require '[pyro.printer :as printer])
                     (printer/swap-stacktrace-engine!)]}}
```

**Comment by pnf** [comment] 2019-05-25 15:41
Hi -
Sorry for the comically late response, but it would have been disappointing even if it were timely: `flycheck-clojure` depends on various linting packages, of which `core.typed` is one.  If the linting package has a bug, or some incompatibility with your code, there's no much we can do other than refer you to the package maintainer, in this case https://github.com/clojure/core.typed.  
If the problem is related to communication between `flycheck-clojure` and the linter, then I'm happy to investigate.  The `README` explains how to invoke the linters manually from the REPL to help isolate the problem.
I'm closing this issue, but feel free to create a new one if you do find a problem with `flycheck-clojure` specifically.

**Closed by pnf** 2019-05-25 15:41 UTC
